<!-- 
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */ -->
<?php
$collection = $block->getCategoryBlog();
$limit = $block->getHelper()->getCharacterLimit();
if ($collection->getSize()):
    foreach ($collection as $blog) {
        $category = $blog->getCategory();
    } ?>
    <h4 class='WK_textcolor wk-heading'><?= /* @noEscape */ $block->escapeHtml($category); ?></h4>
    <div class='container'>
        <?php foreach ($collection as $blog) { ?>
            <div class='wk-blog-block'>
                <h2 class='WK_textcolor'>
                    <a href='<?= /* @noEscape */ $block->escapeHtml($block->getUrl()); ?>
                    wkblog/blog/title/blogid/<?= /* @noEscape */ $block->escapeHtml($blog->getId()); ?>' 
                    role='button' class='btn'>
                        <div class='title'><?= /* @noEscape */ $block->escapeHtml($blog->getSubject()); ?></div>
                    </a>
                </h2>
                <p class='post-meta tags' style='margin-top:20px;'>
                    <span class='date'><?= /* @noEscape */ $block->escapeHtml($blog->getCreatedAt());  ?> </span>
                    <a href='<?= /* @noEscape */ $block->escapeHtml($block->getUrl()); ?>
                    wkblog/blog/user/userid/<?= /* @noEscape */ $block->escapeHtml($blog->getUserId()); ?>'
                    role='button' class='btn'>
                        <span class='author'>
                            <?= /* @noEscape */ $block->escapeHtml($blog->getCustomerName()); ?>
                        </span>
                    </a>
                    <a
                     href='<?= /* @noEscape */ $block->escapeHtml($block->getUrl()); ?>
                     wkblog/category/category/categoryid/
                     <?= /* @noEscape */ $block->escapeHtml($blog->getCategoryId()); ?>'
                        role='button' class='btn'>
                        <span class='cats'>
                            <?= /* @noEscape */ $block->escapeHtml($blog->getCategory()) ?>
                        </span>
                    </a>
                </p>
                <?php
                if (strlen($blog->getContent()) > $limit) {
                    $content = substr(strip_tags($blog->getContent()), 0, $limit) . "...";
                } else {
                    $content = strip_tags($blog->getContent());
                }
                ?>
                <div class='WK_tbodyingedit_content'><?= /* @noEscape */ $content; ?></div>
                <p class='tags'>
                    <span class='tag'>
                        <?php $tags = $blog->getTag();
                        $tagsArray = explode(',', $tags);
                        foreach ($tagsArray as $tag): ?>
                            <?php if ($tag != ""): ?>
                                <a 
                                href='<?= /* @noEscape */ $block->escapeHtml($block->getUrl()); ?>
                                wkblog/blog/tag/tag/
                                <?= /* @noEscape */ $block->escapeHtml($tag); ?>'
                                    role='button' class='btn'>
                                    <span class='tag'>
                                        <?= /* @noEscape */ $block->escapeHtml($tag); ?> ,
                                    </span>
                                </a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </span>
                </p>
                <hr>
            </div>
        <?php } ?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
            <div class='wk-footer'>
                <div class="buttons-set">
                    <p class="back-link">
                        <a class="left" onclick="javascript: window.history.back();" href="javascript:;">« Back</a>
                    </p>
                </div>
            </div>
    </div>
<?php endif; ?>
<?php endif; ?>