<!-- 
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */ -->
<?php
$comment = $block->getComments();
$customer = $block->getCustomerData();
$customerId = $customer->getId();
$commentSize = $block->getCommentSize();
$collection = $block->getTitle();
$isLoggedIn = $block->getHelper()->getCustomerLoginInfo();
?>
<?php foreach ($collection as $blog) : ?>
    <?php $name = $blog->getCustomerName(); ?>
<?php endforeach; ?>
<div class="wk-main-title-container">
    <div class="image-title-container">
        <img src="<?= /* @noEscape */ $block->getUrl("media/wysiwyg/blog/") . $blog->getBlogPic(); ?>">
        <div class="title-time-container">
            <h1 class='WK_textcolor wk-heading'><?= /* @noEscape */ $block->escapeHtml($blog->getSubject()); ?></h1>
            <span class='date'>
                <?php
                $time = strtotime($blog->getCreatedAt());
                $newformat = date('F d, Y', $time);
                ?>
                <?= /* @noEscape */ $block->escapeHtml($newformat);  ?>
            </span>
        </div>
    </div>
    <div class='container'>
        <div class="auther-image-detail">
            <div class="author-image">
                <img src="<?= /* @noEscape */ $block->getUrl("media/wysiwyg/blog/") . $blog->getBlogPic(); ?>" alt="">
            </div>

            <p class='post-meta tags'>
                <!-- <span class='date'>
                <?= /* @noEscape */ $block->escapeHtml($blog->getCreatedAt());  ?>
            </span> -->
                <a href='<?= /* @noEscape */ ($block->getUrl()); ?>wkblog/blog/user/userid/<?= /* @noEscape */ ($blog->getUserId()); ?>' role='button' class='btn'>
                    <span class='author'>
                        <?= /* @noEscape */ $block->escapeHtml($blog->getCustomerName()); ?>
                    </span>
                </a>
                <?php if ($blog->getCategory() != "") : ?>
                    <?php if ($blog->getStatus() != 0) : ?>
                        <a href='<?= /* @noEscape */ ($block->getUrl()); ?>
    wkblog/category/category/categoryid/<?= /* @noEscape */ ($blog->getCategoryId()); ?>' role='button' class='btn'>
                            <span class='cats'><?= /* @noEscape */ $block->escapeHtml($blog->getCategory()) ?>
                            </span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>
        <?= /* @noEscape */ "<div class='WK_tbodyingedit_content'>" . $blog->getContent() . "</div>"; ?>
        <p class='tags'>
            <span class='tag '>
                <?php $tags = $blog->getTag();
                $tagsArray = explode(',', $tags);
                if ($tagsArray[0] != null) {
                    $totalTag = count($tagsArray);
                } else {
                    $totalTag = 1;
                }

                if ($totalTag > 0) {
                    $i = 1; ?>
                    <?php foreach ($tagsArray as $tag) : ?>
                        <?php
                        $seperator = '';
                        if ($tag != "") :
                            if ($totalTag != $i) {
                                $seperator = ',';
                            }
                        ?>
                            <a href='<?= /* @noEscape */ ($block->getUrl()); ?>wkblog/blog/tag/tag/<?= /* @noEscape */ ($tag); ?>' role='button' class='btn'>
                                <span class='tag'>
                                    <?= /* @noEscape */ $block->escapeHtml($tag); ?> <?= /* @noEscape */ $seperator; ?>
                                </span>
                            </a>
                        <?php endif; ?>
                <?php $i = $i + 1;
                    endforeach;
                } ?>
            </span>
        </p>
        <hr>
    </div>
    <div class="WK_tbodyingedit_content wk-comment-box">
        <div class='wk_commentlable'>
            <h3>
                <?= /* @noEscape */ $block->escapeHtml(__("COMMENTS")); ?>
                <span>
                    (<?= /* @noEscape */ $block->escapeHtml($commentSize); ?>)
                </span>
            </h3>
            <div class="WK_tdpadfirstedit">
                <a role="button" href="#" target="_blank" onclick="return false;">
                </a>
            </div>
        </div>
        <?php foreach ($comment as $comments) : ?>
            <div class="WK_tbodyingedit_content wk-comment-style">
                <div class="wk-commentbody">
                    <div class='wk-fb-image'>
                    </div>
                </div>
                <span class="wk_textarea comments_text">
                    <span class="wk_textarea">
                        <?php if ($comments->getCustomerWebsite() != "") : ?>
                            <a href="<?= /* @noEscape */ $block->escapeHtml($comments->getCustomerWebsite()); ?>" rel="nofollow">
                                <?= /* @noEscape */ $block->escapeHtml($comments->getCustomerName());
                                " : " ?>
                            </a>
                        <?php else : ?>
                            <span style='color:#006bb4;' rel="nofollow">
                                <?= /* @noEscape */ $block->escapeHtml($comments->getCustomerName());
                                " : " ?>
                            </span>
                        <?php endif; ?>
                    </span>
                    <p><?= /* @noEscape */ $block->escapeHtml($comments->getComment()); ?></p>
                </span>
            </div>
        <?php endforeach; ?>
        <div class="greet welcome" data-bind="scope: 'customer'">
            <form action="<?= /* @noEscape */ $block->escapeHtml($block->getUrl('wkblog/comment/postcomment/')) ?>" method="post" id="commentSave" enctype="multipart/form-data">
                <?php foreach ($collection as $blog) : ?>

                    <input type="hidden" name="url" data-bind="value:customer().fullname" />
                    <input type="hidden" name="customer_email" data-bind="value:customer().email" id="customer_email" />
                    <input type="hidden" name="post_id" value="<?= /* @noEscape */ $block->escapeHtml($blog->getId()); ?>" />
                    <input type="hidden" name="title" value="<?= /* @noEscape */ $block->escapeHtml($blog->getSubject()); ?>" />
                    <div class="wk-lowercommentbox">
                        <input class="wk_textbox wk-textbox-comment comment" required="1" type="text" placeholder="<?= /* @noEscape */ __("Please enter your full name"); ?>" name="customer_name" id="fullName" data-bind="value:customer().fullname" />
                        <span class="error" id="fullnameErr"></span>
                        <input class="wk_textbox wk-textbox-comment comment" type="url" id="website" placeholder="<?= /* @noEscape */ __("Please enter website"); ?>" name="customer_website" />
                        <span class="error" id="websiteErr"></span>
                        <textarea class="wk_textarea comment" name="comment" id="comment" placeholder="<?= /* @noEscape */ __("Add a comment..."); ?>" required="1" title="<?= /* @noEscape */ __("Add a comment..."); ?>"></textarea>
                        <span class="error" id="commentErr"></span>
                        <div class="wk-comment-save-button">
                            <!-- ko if: customer().fullname  -->
                            <button class="wk_commentbutton" id="commentSubmit" type="submit">
                                <?= /* @noEscape */ $block->escapeHtml(__("Comment")); ?>
                            </button>
                            <!-- /ko -->
                            <!-- ko ifnot: customer().fullname  -->
                            <div class="wk_commentbutton" id="click-me">
                                <?= /* @noEscape */ $block->escapeHtml(__("Comment")); ?>
                            </div>
                            <!-- /ko -->
                        </div>
                        <br>
                    </div>

                <?php endforeach; ?>
            </form>
        </div>
        <div class="order-products-toolbar toolbar bottom">
            <div class='ek-pager-box'>
                <?php if ($block->getPagerHtml()) : ?>
                    <?= /* @noEscape */ $block->getPagerHtml(); ?>
                <?php endif; ?>
            </div>
            <div class="buttons-set" style="clear:left">
                <a class="left" onclick="javascript: window.history.back();" href="javascript:;">« Back</a>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
        "*": {
            "title":{},
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                        
                    }
                }
            },
            "popup": {}
        }
    }
</script>


    <div id="popup-modal" style="display:none;">
        <input type="text" id="email" placeholder="Please enter your email id">
        <span id="emailErr"></span>
    </div>