<?php
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_Blog
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */
$collection =$block->getBlogByName();
$limit = $block->getHelper()->getCharacterLimit();
if ($collection->getSize()): ?>
    <?php foreach ($collection as $blog): ?>
        <?php $name=$blog->getCustomerName(); ?>
    <?php endforeach; ?>
    <h4 class='WK_textcolor wk-heading'><?= /* @noEscape */ $block->escapeHtml($name); ?></h4>
    <div class = 'container'>
        <?php foreach ($collection as $blog): ?>
            <div class='wk-blog-block'>
                <h2 class='WK_textcolor'>
<a 
href='<?= /* @noEscape */ ($block->getUrl()); ?>wkblog/blog/title/blogid/<?= /* @noEscape */($blog->getId());?>'
role='button' class='btn'>
    <div class='title'><?= /* @noEscape */ $block->escapeHtml($blog->getSubject());?></div>
</a>
                </h2>
                <p class = 'post-meta tags' style='margin-top:20px;'>
                    <span class='date'><?= /* @noEscape */ $block->escapeHtml($blog->getCreatedAt()); ?></span> 
<a
href='<?= /* @noEscape */ ($block->getUrl()); ?>wkblog/blog/user/userid/<?= /* @noEscape */($blog->getUserId());?>'
role='button' class='btn'>
<span class='author'>
            <?= /* @noEscape */  $block->escapeHtml($blog->getCustomerName());?> 
</span>
</a>
                    <?php if ($blog->getCategory() != ""): ?>
                        <?php if ($blog->getStatus() != 0): ?>
<a
href='<?= /* @noEscape */($block->getUrl()); ?>wkblog/category/category/categoryid/
                            <?= /* @noEscape */($blog->getCategoryId());?>'
role='button' class='btn'>
<span class='cats'><?= /* @noEscape */ $block->escapeHtml($blog->getCategory())?></span>
</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
                <?php if (strlen($blog->getContent()) > $limit): ?>
                    <?php $content = substr(strip_tags($blog->getContent()), 0, $limit)."..."; ?>
                <?php else: ?>
                    <?php $content = strip_tags($blog->getContent()); ?>
                <?php endif; ?>
                <?= /* @noEscape */  "<div class='WK_tbodyingedit_content'>".$content."</div>"; ?>
                <p class='tags'>
                <span class='tag'>
                                    <?php $tags = $blog->getTag();
                                    $tagsArray = explode(',', $tags);
                                   
                                    ?>
                                    <?php
                                    if ($tagsArray[1] != null) {
                                        $totalTag = count($tagsArray);
                                    } else {
                                        $totalTag = 1;
                                    }
                                    if ($totalTag > 0) {
                                        $i = 1;
                                        foreach ($tagsArray as $tag):
                                            $seperator =  ''; ?>
                                            <?php if ($tag != "") {?>
                                                <?php
                                                if ($totalTag != $i) {
                                                    $seperator = ',';
                                                }
                                                ?>
<a
href='<?= /* @noEscape */ ($block->getUrl()); ?>wkblog/blog/tag/tag/<?= /* @noEscape */  ($tag);?>'
role='button' class='btn'>
<span class='tag'> <?= /* @noEscape */ $block->escapeHtml($tag);?><?= /* @noEscape */  $seperator;?> 
</span>
</a>
                                                <?php
                                            }
                                            $i = $i +1; ?>
                                        <?php endforeach;
                                    } ?>
                                </span>
                  
                </p>
                <hr>
            </div>
        <?php endforeach; ?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
        <?php endif ?>
        <div class='wk-footer'>
            <div class="buttons-set">
                <p class="back-link">
                    <a class="left" onclick="javascript: window.history.back();" href="javascript:;">« Back</a>
                </p>
            </div>
        </div>
    </div>
<?php else: ?>
        <?= /* @noEscape */  "<div class='WK_textcolor'>".__("No post exist by this user")."</div>"; ?>
<?php endif; ?>